[project]
name = "learning-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "curl-cffi>=0.7.4",
    "pygame-ce>=2.5.2",
    "pyqt6>=6.8.0",
    "pyside6>=6.8.1",
    "requests>=2.32.3",
]
